export const specialOccasions = [
  "Casamientos",
  "Bautismos",
  "Comuniones",
  "Confirmaciones",
  "Primeras Comuniones",
  "Bendiciones",
  "Consagraciones",
  "Dedicaciones",
  "Aniversarios",
  "Celebraciones Especiales",
];

const songs = [
  {
    title: "Cristo Joven",
    lyrics: [
      { chord: "C", text: "Ven hermano y cántale a Cristo" },
      { chord: "Em", text: "" },
      { chord: "F", text: "A ese Cristo joven que un día nos redimió" },
      { chord: "G G7", text: "" },
      { chord: "C", text: "Haz de tu amor una plegaria" },
      { chord: "Em", text: "" },
      { chord: "F", text: "Un simple canto alegre que el Señor escuchará" },
      { chord: "G G7", text: "" },
      { chord: "C", text: "No te alejes del camino marcado" },
      { chord: "Em", text: "" },
      { chord: "F", text: "Que Cristo ha señalado para acercarnos a Él" },
      { chord: "G G7", text: "" },
      { chord: "C", text: "Devuélvele con fe inquebrantable" },
      { chord: "Em", text: "" },
      { chord: "F", text: "Tanto amor incuestionable que nos ha ofrecido Él" },
      { chord: "G", text: "" },
      { chord: "C", text: "Ven aquí, canta ya" },
      { chord: "Em", text: "" },
      { chord: "F", text: "No te olvides tú de Cristo" },
      { chord: "G", text: "" },
      { chord: "C", text: "Piensa que, en la cruz" },
      { chord: "Em", text: "" },
      { chord: "F", text: "Por nosotros El se dio" },
      { chord: "G", text: "" },
    ],
    categories: {
      massParts: ["Entrada", "Comunión"],
      liturgicalSeasons: ["Domingo", "Tiempo Ordinario"],
      specialOccasions: ["Bautismos", "Comuniones", "Confirmaciones"],
    },
  },
  {
    title: "Alma misionera",
    lyrics: [
      { chord: "SOL", text: "Señor, toma mi vida nueva" },
      { chord: "RE", text: "" },
      { chord: "MIm", text: "" },
      { chord: "DO", text: "" },
      { chord: "SOL", text: "Antes de que la espera, desgaste años en mi" },
      { chord: "RE", text: "" },
      { chord: "SOL", text: "Estoy dispuesto a lo que quieras" },
      { chord: "RE", text: "" },
      { chord: "MIm", text: "" },
      { chord: "DO", text: "" },
      { chord: "SOL", text: "No importa lo que sea" },
      { chord: "RE", text: "" },
      { chord: "SOL", text: "Tu llamame a servir" },
      { chord: "RE7", text: "" },
      { chord: "SOL", text: "Te doy mi corazon sincero" },
      { chord: "RE", text: "" },
      { chord: "MIm", text: "" },
      { chord: "DO", text: "" },
      { chord: "SOL", text: "Para gritar sin miedo tu grandeza señor" },
      { chord: "RE", text: "" },
      { chord: "SOL", text: "Tendré, tus manos sin cansancio" },
      { chord: "RE", text: "" },
      { chord: "MIm", text: "" },
      { chord: "DO", text: "" },
      { chord: "SOL", text: "Tu historia entre mis labios" },
      { chord: "RE", text: "" },
      { chord: "SOL", text: "Y fuerza en la oración" },
      { chord: "RE7", text: "" },
      { chord: "SOL", text: "LLEVAME DONDE LOS HOMBRES" },
      { chord: "RE", text: "" },
      { chord: "MIm", text: "NECESITEN TUS PALABRAS" },
      { chord: "DO", text: "" },
      { chord: "SOL", text: "NECESITEN MIS GANAS DE VIVIR" },
      { chord: "RE", text: "" },
      { chord: "SOL", text: "DONDE FALTE LA ESPERANZA" },
      { chord: "RE", text: "" },
      { chord: "MIm", text: "DONDE TODO SEA TRISTE" },
      { chord: "DO", text: "" },
      { chord: "SOL/RE", text: "SIMPLEMENTE POR NO SABER DE TI" },
      { chord: "SOL/RE", text: "" },
    ],
    categories: {
      massParts: ["Comunión"],
      liturgicalSeasons: [
        "Domingo",
        "Tiempo Ordinario",
        "Adviento",
        "Cuaresma",
        "Pascua",
        "Navidad",
      ],
      specialOccasions: [
        "Bautismos",
        "Comuniones",
        "Confirmaciones",
        "Casamientos",
      ],
    },
  },
  {
    title: "Vida en abundancia",
    lyrics: [
      { chord: "C", text: "Ven Señor no tardes" },
      { chord: "G", text: "Ven que te esperamos" },
      { chord: "Am", text: "Ven pronto Señor" },
    ],
    categories: {
      massParts: ["Entrada", "Comunión"],
      liturgicalSeasons: ["Tiempo Ordinario"],
      specialOccasions: ["Casamientos"],
    },
  },
  {
    title: "Santo, Santo, Santo",
    lyrics: [
      { chord: "D", text: "Santo, Santo, Santo, Señor del universo" },
      { chord: "A", text: "Llenos están el cielo y la tierra de tu gloria" },
    ],
    categories: {
      massParts: ["Santo"],
      liturgicalSeasons: ["Tiempo Ordinario", "Pascua"],
      specialOccasions: [
        "Bautismos",
        "Comuniones",
        "Confirmaciones",
        "Casamientos",
      ],
    },
  },
];

export default songs;
